version: '3.10'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
  web:
    build: .
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8070
    ports:
      - "8070:8070"
    environment:
      - SECRET_KEY=django-insecure-+3&f#!jy1^omf2@8@ewu^id5u_hm-7dqy&xdwa5guos820ifg@
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=127.0.0.1 localhost 0.0.0.0
      - PG_NAME=postgres
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_PORT=5432
      - PG_HOST=db
    depends_on:
      - db