# Generated by Django 4.1.4 on 2023-01-20 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_contact_alter_comment_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
