# Generated by Django 4.1.4 on 2023-01-21 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
