# Generated by Django 4.1.4 on 2023-01-21 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_userprofile_delete_webuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
